# -*- coding: utf-8 -*-
"""cleaning_phase.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1riV9dlPFC9j_NNUSatE2k1azNTfEnxrf

Import pandas library to view, clean and transform data
"""

import pandas as pd

sheets = pd.read_excel('/Manufacturing_Line_Productivity.xlsx', sheet_name = None)
print(sheets.keys())

"""View first sheet : line productivity"""

Line_Productivity = sheets['Line productivity']
Line_Productivity.info()

Line_Productivity['Date'] = Line_Productivity['Date'].dt.strftime('%Y-%m-%d')
Line_Productivity['Start Time'] = Line_Productivity['Start Time'].dt.strftime('%H:%M:%S')
Line_Productivity

"""View second sheet products"""

Products = sheets['Products']
Products.info()

"""View third sheet : downtime factors"""

Downtime_Factors = sheets['Downtime factors']
Downtime_Factors.info()

"""View fourth sheet : line downtime"""

Line_Downtime = sheets['Line downtime']
Line_Downtime.info()

Line_Downtime.head()

"""Data in line downtime sheet needs cleaning , first use first row as a header"""

Line_Downtime.columns = Line_Downtime.iloc[0]
Line_Downtime = Line_Downtime[1:]
Line_Downtime.head()

"""second step , unpivot table"""

Line_Downtime_unpivot = pd.melt(Line_Downtime, id_vars=['Batch'], var_name='Factor',value_name='Downtime')
print(Line_Downtime_unpivot)

"""remove null values"""

Line_Downtime_cleaned = Line_Downtime_unpivot.dropna()

print(Line_Downtime_cleaned)

"""Save the new cleaned file"""

from os import write
with pd.ExcelWriter('/content/Manfacturing_Line_Productivity_cleaned.xlsx') as writer:
  Line_Productivity.to_excel(writer,sheet_name = 'Line_Productivity',index=False)
  Products.to_excel(writer,sheet_name = 'Products',index=False)
  Downtime_Factors.to_excel(writer,sheet_name = 'Downtime_Factors',index=False)
  Line_Downtime_cleaned.to_excel(writer,sheet_name = 'Line_Downtime',index=False)